SELECT nombre FROM tienda.producto;
SELECT nombre, precio FROM tienda.producto;
SHOW COLUMNS  FROM  tienda.producto;
SELECT nombre, precio AS euros, ROUND(precio*1.11, 2) AS dolars FROM tienda.producto;
SELECT nombre AS "nom de producto" , precio AS euros, ROUND(precio*1.11,2) AS dolars FROM tienda.producto;
SELECT UCASE(nombre), precio FROM tienda.producto;
SELECT LCASE(nombre), precio FROM tienda.producto;
SELECT nombre, CONCAT(UPPER(LEFT(nombre, 2)) , LOWER(SUBSTRING(nombre,3))) AS "2 Majúscules" FROM tienda.fabricante;
SELECT nombre, ROUND(precio) FROM tienda.producto;
SELECT nombre, TRUNCATE(precio,0) FROM tienda.producto;
SELECT codigo_fabricante FROM tienda.producto;
SELECT DISTINCT(codigo_fabricante) FROM tienda.producto;
SELECT nombre FROM tienda.fabricante ORDER BY nombre ASC;
SELECT nombre FROM tienda.fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM tienda.producto ORDER BY  nombre ASC, precio DESC;
SELECT * FROM tienda.fabricante LIMIT 0,5;
SELECT * FROM tienda.fabricante LIMIT 3,2;
SELECT nombre, precio FROM tienda.producto ORDER BY precio LIMIT 0,1;
SELECT nombre, precio FROM tienda.producto ORDER BY precio DESC LIMIT 0,1;
SELECT * FROM tienda.producto WHERE codigo_fabricante = 2;
SELECT p.nombre,precio,f.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo;
SELECT p.nombre,precio,f.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo ORDER BY f.nombre;
SELECT p.codigo,p.nombre,precio,f.codigo,f.nombre  FROM tienda.producto AS p  JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo;
SELECT p.nombre,precio,f.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo ORDER BY precio LIMIT 0,1;
SELECT p.nombre,precio,f.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo ORDER BY precio DESC LIMIT 0,1;
SELECT p.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre='Lenovo' ;
SELECT p.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre='Crucial' AND p.precio>200;
SELECT p.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' OR  f.nombre = 'Hewlett-Packard' OR  f.nombre = 'Seagate';
SELECT p.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre IN('Asus','Hewlett-Packard','Seagate');
SELECT p.nombre,precio FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e';
SELECT p.nombre,precio FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
SELECT p.nombre,precio,f.nombre FROM tienda.producto AS p JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE precio >= 180 ORDER BY precio DESC, p.nombre ASC;
SELECT DISTINCT f.codigo, f.nombre FROM tienda.fabricante AS f JOIN producto AS p ON f.codigo = p.codigo_fabricante;
SELECT f.nombre, p.nombre FROM tienda.fabricante AS f LEFT JOIN producto AS p ON f.codigo = p.codigo_fabricante;
SELECT f.nombre FROM tienda.fabricante AS f LEFT JOIN producto AS p ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IS NULL;
SELECT p.nombre FROM tienda.fabricante AS f, tienda.producto AS p WHERE f.codigo=p.codigo_fabricante AND f.nombre='Lenovo';
SELECT p.nombre FROM tienda.fabricante AS f, tienda.producto AS p WHERE f.codigo=p.codigo_fabricante AND  p.precio = (SELECT MAX(precio) FROM tienda.fabricante AS f, tienda.producto AS p WHERE f.codigo=p.codigo_fabricante AND  f.nombre='Lenovo');
SELECT p.nombre FROM tienda.fabricante AS f, tienda.producto AS p WHERE f.codigo=p.codigo_fabricante AND f.nombre='Lenovo' ORDER BY precio DESC LIMIT 0,1 ;
SELECT p.nombre FROM tienda.fabricante AS f, tienda.producto AS p WHERE f.codigo=p.codigo_fabricante AND f.nombre='Hewlett-Packard' ORDER BY precio LIMIT 0,1 ;
SELECT p.nombre FROM tienda.fabricante AS f JOIN tienda.producto AS p ON f.codigo=p.codigo_fabricante WHERE p.precio >= (SELECT MAX(precio) FROM tienda.fabricante AS f JOIN tienda.producto AS p ON f.codigo=p.codigo_fabricante WHERE  f.nombre='Lenovo');
SELECT p.nombre FROM tienda.fabricante AS f JOIN tienda.producto AS p ON f.codigo=p.codigo_fabricante WHERE p.precio > (SELECT AVG(precio) FROM tienda.fabricante AS f JOIN tienda.producto AS p ON f.codigo=p.codigo_fabricante WHERE  f.nombre='Asus') AND f.nombre='Asus';